### ISSUE TITLE
Can't peer Striker

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/anvil#405]
Failed with a 500 error trying to peer the Striker.

![Screenshot from 2023-08-05 14-42-50](https://github.com/ClusterLabs/anvil/assets/189162/c4fe90fc-60c2-4318-9327-d4d50aca03a1)

**Comment by digimer** [comment]
I tried peering again using the 'admin' user, but same result. From the second attempt, I saw these logs in journald;

```
-- Logs begin at Sun 2023-07-30 22:44:25 EDT. --
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Get session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "scriptId": "211a7cc5-cb89-49c2-9c36-022ccaaef4d6",
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "script": "r SELECT s.session_uuid, u.user_uuid, s.modified_date FROM sessions AS s JOIN users AS u ON s.session_user_uuid = u.user_uuid WHERE s.session_salt != 'DELETED' AND s.session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Variables: {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "sessionModifiedDate": "2023-08-05 14:44:35.005356-04",
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "sessionDeadlineEpoch": 1691289875005,
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "cookieMaxAge": 28707454
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Deserialize user identified by 83389234-cb90-48a0-ae7f-a6dbcce2f545
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "scriptId": "560823f6-1da5-42e4-8c61-f7f498f3b0a8",
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "script": "r SELECT user_name FROM users WHERE user_algorithm != 'DELETED' AND user_uuid = '83389234-cb90-48a0-ae7f-a6dbcce2f545';\n"
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Query stdout pre-hooks (type=[object]): [
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   [
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:     "admin"
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   ]
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: ]
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Query stdout post-hooks (type=[object]): {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "admin": {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:     "jobProgress": null,
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:     "jobUUID": "admin"
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Touch session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63: {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "session": {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:     "cookie": {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:       "originalMaxAge": 28800000,
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:       "expires": "2023-08-06T02:46:07.554Z",
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:       "httpOnly": true,
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:       "path": "/"
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:     },
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:     "passport": {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:       "user": "83389234-cb90-48a0-ae7f-a6dbcce2f545"
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:     }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "scriptId": "99c9b4c9-b244-4361-8b92-23ffca0b5702",
Aug 05 14:46:07 an-striker01.alteeve.com node[819]:   "script": "w UPDATE sessions SET modified_date = '2023-08-05 14:46:07.557530932-04:00' WHERE session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Generated session identifier eff9b720-7997-41cf-b695-cfebf991a91c; access to /api/ssh-key/conflict
Aug 05 14:46:07 an-striker01.alteeve.com node[819]: Unauthenticated access to /api/ssh-key/conflict
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Get session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "scriptId": "ac723507-7ea7-459e-b484-8fc6bd0c62b8",
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "script": "r SELECT s.session_uuid, u.user_uuid, s.modified_date FROM sessions AS s JOIN users AS u ON s.session_user_uuid = u.user_uuid WHERE s.session_salt != 'DELETED' AND s.session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Variables: {
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "sessionModifiedDate": "2023-08-05 14:46:07.557531-04",
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "sessionDeadlineEpoch": 1691289967557,
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "cookieMaxAge": 28792590
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Deserialize user identified by 83389234-cb90-48a0-ae7f-a6dbcce2f545
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "scriptId": "9ea6008a-2152-4275-b88a-7a6e2d560811",
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "script": "r SELECT user_name FROM users WHERE user_algorithm != 'DELETED' AND user_uuid = '83389234-cb90-48a0-ae7f-a6dbcce2f545';\n"
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Calling CLI script to get data.
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: localHostUUID=[3e11359f-8612-44a2-a915-a51314f8feac]
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: condHostUUIDs=[ip_add.ip_address_host_uuid = '3e11359f-8612-44a2-a915-a51314f8feac']
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "scriptId": "15513a38-d43b-456c-8f8e-efd32be54983",
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:   "script": "x data->database\n"
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: Failed to complete DB write in touch session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63; CAUSE: AssertionError [ERR_ASSERTION]: Write exited with code undefined
Aug 05 14:46:14 an-striker01.alteeve.com node[819]: AssertionError [ERR_ASSERTION]: Write exited with code undefined
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:     at /usr/share/striker-ui-api/index.js:2:1295913
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:     at p (/usr/share/striker-ui-api/index.js:2:946195)
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:     at Generator.<anonymous> (/usr/share/striker-ui-api/index.js:2:947513)
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:     at Generator.next (/usr/share/striker-ui-api/index.js:2:946605)
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:     at yn (/usr/share/striker-ui-api/index.js:2:1289776)
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:     at a (/usr/share/striker-ui-api/index.js:2:1289980)
Aug 05 14:46:14 an-striker01.alteeve.com node[819]:     at process._tickCallback (internal/process/next_tick.js:68:7)
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: Get session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "scriptId": "103ca1a9-a202-40fd-8278-f0917a923781",
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "script": "r SELECT s.session_uuid, u.user_uuid, s.modified_date FROM sessions AS s JOIN users AS u ON s.session_user_uuid = u.user_uuid WHERE s.session_salt != 'DELETED' AND s.session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: Variables: {
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "sessionModifiedDate": "2023-08-05 14:46:07.557531-04",
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "sessionDeadlineEpoch": 1691289967557,
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "cookieMaxAge": 28787794
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: Deserialize user identified by 83389234-cb90-48a0-ae7f-a6dbcce2f545
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "scriptId": "77e57446-f444-4299-92e5-55db323a65ff",
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "script": "r SELECT user_name FROM users WHERE user_algorithm != 'DELETED' AND user_uuid = '83389234-cb90-48a0-ae7f-a6dbcce2f545';\n"
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "scriptId": "773777d6-0c9b-41c0-b326-9394bd275d48",
Aug 05 14:46:19 an-striker01.alteeve.com node[819]:   "script": "x Striker->get_peer_data \"{\\\"password\\\":\\\"super secret password\\\",\\\"port\\\":0,\\\"target\\\":\\\"10.201.4.2\\\"}\"\n"
Aug 05 14:46:19 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: data->database data: "1"
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: connections=[{
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "local": {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     "inbound": {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "ipAddress": {},
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "port": 5432,
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "user": "admin"
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     },
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     "peer": {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "undefined": {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:         "hostUUID": "0",
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:         "isPing": false,
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:         "port": null
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: }]
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "scriptId": "66a0d63d-8216-4f32-9038-9c2e96688d8e",
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "script": "r SELECT ip_add.ip_address_uuid, ip_add.ip_address_host_uuid, ip_add.ip_address_address, CASE WHEN ip_add.ip_address_on_type = 'interface' THEN net_int.network_interface_name ELSE bon.bond_active_interface END AS network_name FROM ip_addresses AS ip_add LEFT JOIN network_interfaces AS net_int ON ip_add.ip_address_on_uuid = net_int.network_interface_uuid LEFT JOIN bridges AS bri ON ip_add.ip_address_on_uuid = bri.bridge_uuid LEFT JOIN bonds AS bon ON bri.bridge_uuid = bon.bond_bridge_uuid OR ip_add.ip_address_on_uuid = bon.bond_uuid WHERE ip_add.ip_address_host_uuid = '3e11359f-8612-44a2-a915-a51314f8feac' AND ip_add.ip_address_note != 'DELETED';\n"
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: Variables: {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "sessionModifiedDate": "10.201.4.1",
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "sessionDeadlineEpoch": null,
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "cookieMaxAge": null
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: Deserialize user identified by 3e11359f-8612-44a2-a915-a51314f8feac
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "scriptId": "f6a23fd2-f9d5-4a1a-939f-6ad0b12976d7",
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "script": "r SELECT user_name FROM users WHERE user_algorithm != 'DELETED' AND user_uuid = '3e11359f-8612-44a2-a915-a51314f8feac';\n"
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: Unauthenticated access to /api/host/local
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: Set session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63: {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   "session": {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     "cookie": {
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "originalMaxAge": 28800000,
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "expires": "2023-08-06T02:46:21.571Z",
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "httpOnly": true,
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:       "path": "/"
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     },
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     "passport": {}
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:   }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: Failed to complete DB write in set session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63; CAUSE: AssertionError [ERR_ASSERTION]: Missing user identifier
Aug 05 14:46:21 an-striker01.alteeve.com node[819]: AssertionError [ERR_ASSERTION]: Missing user identifier
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at /usr/share/striker-ui-api/index.js:2:1294558
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at p (/usr/share/striker-ui-api/index.js:2:946195)
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at Generator.<anonymous> (/usr/share/striker-ui-api/index.js:2:947513)
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at Generator.next (/usr/share/striker-ui-api/index.js:2:946605)
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at yn (/usr/share/striker-ui-api/index.js:2:1289776)
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at a (/usr/share/striker-ui-api/index.js:2:1289980)
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at /usr/share/striker-ui-api/index.js:2:1290041
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at new Promise (<anonymous>)
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at f.<anonymous> (/usr/share/striker-ui-api/index.js:2:1289920)
Aug 05 14:46:21 an-striker01.alteeve.com node[819]:     at f.t.value (/usr/share/striker-ui-api/index.js:2:1295521)
Aug 05 14:46:24 an-striker01.alteeve.com scancore[816]: ----=] ScanCore loop finished after: [6]. Sleeping for: [60] seconds. ]=--------------------------------------
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Get session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "scriptId": "56694ae2-b06f-47f5-9ce4-b2d7104a585a",
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "script": "r SELECT s.session_uuid, u.user_uuid, s.modified_date FROM sessions AS s JOIN users AS u ON s.session_user_uuid = u.user_uuid WHERE s.session_salt != 'DELETED' AND s.session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Striker->get_peer_data results: undefined
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Failed to get peer data; CAUSE: TypeError: Invalid attempt to destructure non-iterable instance.
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Touch session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63: {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "session": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     "cookie": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "originalMaxAge": 28800000,
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "expires": "2023-08-06T02:46:26.585Z",
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "httpOnly": true,
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "path": "/"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     },
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     "passport": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "user": "83389234-cb90-48a0-ae7f-a6dbcce2f545"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "scriptId": "3bbfa720-4b3a-48e7-86f2-7fa5610723f2",
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "script": "w UPDATE sessions SET modified_date = '2023-08-05 14:46:26.587524956-04:00' WHERE session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Query stdout pre-hooks (type=[object]): {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "write_code": 0
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Query stdout post-hooks (type=[object]): {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "write_code": 0
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Touch session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63: {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "session": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     "cookie": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "originalMaxAge": 28800000,
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "expires": "2023-08-06T02:46:26.603Z",
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "httpOnly": true,
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "path": "/"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     },
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     "passport": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "user": "83389234-cb90-48a0-ae7f-a6dbcce2f545"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "scriptId": "a252f1a3-4f9e-48a2-abb7-d313f466e8ab",
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "script": "w UPDATE sessions SET modified_date = '2023-08-05 14:46:26.605607509-04:00' WHERE session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Unauthenticated access to /api/job?start=1691259253
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Set session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63: {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   "session": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     "cookie": {
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "originalMaxAge": 28800000,
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "expires": "2023-08-06T02:46:26.610Z",
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "httpOnly": true,
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:       "path": "/"
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     },
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     "passport": {}
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:   }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: Failed to complete DB write in set session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63; CAUSE: AssertionError [ERR_ASSERTION]: Missing user identifier
Aug 05 14:46:26 an-striker01.alteeve.com node[819]: AssertionError [ERR_ASSERTION]: Missing user identifier
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at /usr/share/striker-ui-api/index.js:2:1294558
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at p (/usr/share/striker-ui-api/index.js:2:946195)
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at Generator.<anonymous> (/usr/share/striker-ui-api/index.js:2:947513)
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at Generator.next (/usr/share/striker-ui-api/index.js:2:946605)
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at yn (/usr/share/striker-ui-api/index.js:2:1289776)
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at a (/usr/share/striker-ui-api/index.js:2:1289980)
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at /usr/share/striker-ui-api/index.js:2:1290041
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at new Promise (<anonymous>)
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at f.<anonymous> (/usr/share/striker-ui-api/index.js:2:1289920)
Aug 05 14:46:26 an-striker01.alteeve.com node[819]:     at f.t.value (/usr/share/striker-ui-api/index.js:2:1295521)
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: Get session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:   "scriptId": "b598e0fa-6d8e-4ab8-a1b1-6252934590c3",
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:   "script": "r SELECT s.session_uuid, u.user_uuid, s.modified_date FROM sessions AS s JOIN users AS u ON s.session_user_uuid = u.user_uuid WHERE s.session_salt != 'DELETED' AND s.session_uuid = '3d3b74ac-a8c2-4569-8fe2-6f499f77eb63';\n"
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: Variables: {
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:   "sessionModifiedDate": "2023-08-05 14:46:26.605608-04",
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:   "sessionDeadlineEpoch": 1691289986605,
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:   "cookieMaxAge": 28794983
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: Deserialize user identified by 83389234-cb90-48a0-ae7f-a6dbcce2f545
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: Access interact: {
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:   "scriptId": "3f7c8db9-060f-4547-ab72-1f30836697fa",
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:   "script": "r SELECT user_name FROM users WHERE user_algorithm != 'DELETED' AND user_uuid = '83389234-cb90-48a0-ae7f-a6dbcce2f545';\n"
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: }
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: Failed to complete DB write in touch session 3d3b74ac-a8c2-4569-8fe2-6f499f77eb63; CAUSE: AssertionError [ERR_ASSERTION]: Write exited with code undefined
Aug 05 14:46:31 an-striker01.alteeve.com node[819]: AssertionError [ERR_ASSERTION]: Write exited with code undefined
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:     at /usr/share/striker-ui-api/index.js:2:1295913
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:     at p (/usr/share/striker-ui-api/index.js:2:946195)
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:     at Generator.<anonymous> (/usr/share/striker-ui-api/index.js:2:947513)
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:     at Generator.next (/usr/share/striker-ui-api/index.js:2:946605)
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:     at yn (/usr/share/striker-ui-api/index.js:2:1289776)
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:     at a (/usr/share/striker-ui-api/index.js:2:1289980)
Aug 05 14:46:31 an-striker01.alteeve.com node[819]:     at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by digimer** [comment]
After this, nothing in the WebUI would respond. Clicking on anything, even manually typing the URL would load until it timed out. After rebooting, the UI was responsive again.

**Comment by ylei-tsubame** [comment]
The logs doesn't show the cause of the error. If possible, can I get the logs covering the duration when you are using the UI? I'll try to figure out the cause on my end regardless.

If something similar happens, only restart `striker-ui-api.service`.
